export const Slider = [
    {
      EducationTitle: "Education",
      Degree: "Bachelor of Science in Computer Science",
      Date: "Jan 2019 - Dec 2022",
      University: "Brigham Young University - Idaho",
      Location: "Rexburg, Idaho, United States",
      Coursework: "Object-Oriented Software Development, Web Engineering I, Data Structures, Database & Design Development, Software Design and Development, Web Engineering II, Software Engineering III, Comp. Communication &Networks, Systems Security I, Discrete Mathematics I, Data Science Programming, Machine Learning and Data Mining, Computer Security, Parallelism and Concurrency, Big Data Programming and Analytics, Algorithms & Complexity, Linear Algebra, Applied Calculus for Data Analysis, Clojure.",
      Certificates: "Computer Programming · Machine Learning Fundamentals · CISCO - Introduction to Cybersecurity."
    },
    {
       ExperienceTitle: "Work Experience",
       JobTitle: "Software Test Engineer (Internship)",
       Date: "Jan 2023 - Present",
       Company: "The Church of Jesus Christ of Latter-day Saints",
       Location: "Riverton, Utah, United States",
       FirstJobDetail: "Contributed to over 170 user stories in Azure DevOps by conducting regression testing, analyzing results, and submitting observations to the development team.",
       SecondJobDetail: "Participated in design reviews to identify inconsistencies//issues in product requirements by interacting with business analysts and developers during the sprint cycle.",
       ThirdJobDetail: "Performed integration, End-to-End, performance, regression, sanity, and smoke testing on Mobile and Web applications by developing negative and positive test cases according to business requirements.",
       FourthJobDetail: "Created automated test cases using Cypress and executed SQL queries for data validation and debugging.",
       FifthJobDetail: "Assisted with continuous integration and deployment practices in Azure DevOps using an Agile Software Development process.",
       Skills: "Software Testing Life Cycle (STLC) · QA Automation · Test Scripts · JavaScript · SQL · Microsoft Dynamics 365 · Azure DevOps · Git · Visual Studio IDE · Cypress · Agile Software Development."    
    },
    {
        ExperienceTitle: "Work Experience",
        JobTitle: "Software Engineer (Internship)",
        Date: "Sep 2022 - Dec 2022",
        Company: "We Care Insurance",
        Location: "Omaha, Nebraska, United States",
        FirstJobDetail: "Designed, created, and executed automation scripts using Java and Selenium.",
        SecondJobDetail: "Configured test environments for running test cases and scenarios using Spring Tool Suite. Assisted with software testing",
        ThirdJobDetail: "Participated in the deployment of QA processes using software tools and supporting technologies.",
        Skills: " MySQL · XAMPP · Spring Tool Suite · Selenium · Spring Boot · HTML · CSS · JavaScript · Java · GitHub"    
     },
     {
        ExperienceTitle: "Work Experience",
        JobTitle: "Technical Support Representative (Internship)",
        Date: "Nov 2021 - Apr 2022",
        Company: "The Church of Jesus Christ of Latter-day Saints",
        Location: "Salt Lake City, Utah, United States",
        FirstJobDetail: "Technical support on-site for employees in the Salt Lake City area and remotely across the United States and Canada.",
        SecondJobDetail: "Managed IT service requests, events, incidents, and alerts using the Service Now ticketing system.",
        ThirdJobDetail: "Enterprise Active Directory management using tools such as Microsoft Endpoint Manager, JAMF Pro Server for macOS, and ADUC.",
        FourthJobDetail: "Technical support for server directories, network printers, Cisco VoIP phones, physical networks, integration of corporate email on smartphones such as iPhone and Android, and other network devices.",
        FifthJobDetail: "Experience with Microsoft Active Directory, group policies, user profiles within Windows, imaging software, and file/security permissions.",
        SixthJobDetail: "Experience supporting Microsoft cloud-based back-office systems including Azure AD, Exchange, SharePoint/OneDrive, Security & Compliance, ATP, InTune, AutoPilot, and Teams.",
        Skills: ""    
     },
     {
        ExperienceTitle: "Work Experience",
        JobTitle: "IT Incidents Lead Technician (Advanced Technical Suport)",
        Date: "Ago 2021 - Nov 2021",
        Company: "Brigham Young University - Idaho",
        Location: "Rexburg, Idaho, United States",
        FirstJobDetail: "Record and classify received Incidents and undertake an immediate effort to fix Computer issues.",
        SecondJobDetail: "Monitor IT Technicians to ensure they reach their goals and the IT troubleshooting process is performed properly.",
        ThirdJobDetail: "Responsible for assigning incidents within a group of 25 IT Technicians (IT Tier 2).",
        FourthJobDetail: "Escalate unresolved incidents to external support within the University organization.",
        FifthJobDetail: "Document troubleshooting steps and service restoration details.",
        SixthJobDetail: "Investigate and diagnose IT Incidents to restore a failed IT Service as quickly as possible.",
        SeventhJobDetail: "Restore a failed IT Service, repair hardware damage, and troubleshooting software issues as quickly as possible.",
        EigthJobDetail: "Verify resolution with BYU-I students, faculty, Full-time employees, and resolve Incidents in the TeamDynamix tool.",
        Skills: ""    
     },
     {
        ExperienceTitle: "Work Experience",
        JobTitle: "IT Support Technician",
        Date: "Jul 2020 - Ago 2021",
        Company: "Brigham Young University - Idaho",
        Location: "Rexburg, Idaho, United States",
        FirstJobDetail: "IT troubleshooting & problem-solving.",
        SecondJobDetail: "Computer hardware systems & components.",
        ThirdJobDetail: "Answering phone calls and remote technical support.",
        FourthJobDetail: "LAN & WAN Connectivity & Maintenance.",
        FifthJobDetail: "Installing, repairing, maintaining, and upgrading Windows and Mac operating systems.",
        SixthJobDetail: "Troubleshooting Two-factor authentication methods.",
        SeventhJobDetail: "Imaging computers and installing appropriate software for faculty and student employees.",
        EigthJobDetail: "Performing data backups on Onedrive, mapping network drives, and updating Active Directory.",
        NinethJobDetail: "Fixing any type of technical issues including WIFI connectivity, virtual machines, Office 365, AC Cloud, malware, upgrading operating systems, and software installation.",
        Skills: ""    
     }
];